server:
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DB_NAME}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_OPTION}
logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: app/logs/application.log