server:
  port: 8080
  servlet:
    context-path: /api
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DB_NAME}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_OPTION}
    defer-datasource-initialization: true
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${HOST}
      password: ${REDIS_PW}
      geokey: ${REDIS_GEO_KEY}
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    com.gilin: debug
  file:
    name: app/logs/application.log
apikey:
  odsays:
    ${ODSAY_API_CSK}
  tmap:
    ${TMAP_API_DINO}
  seouls:
    ${SEOUL_API_SEO}
  kakaos:
    ${KAKAO_API_SEO}
jwt:
  accessKey: ${JWT_ACCESS_KEY}
  accessPeriod: ${JWT_ACCESS_PERIOD}
  refreshKey: ${JWT_REFRESH_KEY}
  refreshPeriod: ${JWT_REFRESH_PERIOD}
